// Offline exact allowlist for the independently reviewed factual summaries.
// Source-quality approval is distinct from the still-required matching gate.
import "../../../scripts/_smoke-bootstrap";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { parseStorySpecDocument, validateStorySpec } from "../../../lib/story-spec";
import type { StorySpec } from "../../../lib/story-spec-types";
import { THEME_VOCABULARY } from "../../../lib/themes";
import type { FigureStageRow } from "../../../lib/types";

export const factsV2ProposalSha256 = "9427e7e099252b91d7f23b3873fa0a32b9f770a93aa0dcfacc2a47c44e7883ac";
export const factsV2ReviewSha256 = "24986cb92b7e7715bbdac8dbe901b4d20108a267878ed07dd3d68471562111d7";
export const themeV1ProposalSha256 = "5998bcf03e3e9ae672bd4721e1262e2c6dd992618ac6a9486a53f0b3578d838b";
export const themeV1ReviewSha256 = "c79bf47709e4418cd452a4e10bcd692b870564187ed49590a14cf714b311e7de";
export const themeAdditions = {jacobs: "self_invention", riis: "late_start"} as const;
const packet = resolve("docs/releases/new-stories-production-2026-10-02");
const inputs = resolve("docs/research/new-stories-2026-10-02");
const writing = resolve("docs/releases/new-stories-written-2026-10-02");
const sha = (bytes: string | Buffer) => createHash("sha256").update(bytes).digest("hex");
const same = (actual: unknown, expected: unknown, message: string) => assert(isDeepStrictEqual(actual, expected), message);
type ProposalStage = {figureKey: string; stageId: string; file: string; originalWritingStageSha256: string;
  proposedV1StageSha256: string; proposedV2StageSha256: string; originalSha256: string; proposedSha256: string;
  unchangedCandidateFile: string; unchangedCandidateSha256: string; changedFields: string[];
  proposedFactsWords: number; proposedFactsCharacters: number;
  sentenceEvidence: Array<{sentence: string; candidateFactIds: string[]}>};
export type ApprovedV2Input = {figureKey: string; storySpecId: string; candidateSha256: string; stageSha256: string;
  productionStageSha256: string; original: FigureStageRow; proposed: FigureStageRow; draft: StorySpec};

export function readApprovedV2Inputs(): ApprovedV2Input[] {
  const proposalBytes = readFileSync(resolve(packet, "FACTS-PROPOSAL.v2.json"));
  assert.equal(sha(proposalBytes), factsV2ProposalSha256, "The exact independently reviewed facts-v2 proposal changed");
  const proposal = JSON.parse(proposalBytes.toString("utf8")) as {schemaVersion: string; inputDirectory: string; outputDirectory: string;
    changedFieldsFromV1: string[]; stages: ProposalStage[]};
  assert.equal(proposal.schemaVersion, "new-ten-facts-proposal-v2");
  assert.equal(proposal.inputDirectory, "proposed-stages"); assert.equal(proposal.outputDirectory, "facts-v2-stages");
  same(proposal.changedFieldsFromV1, ["biographicalFacts"], "V2 proposal scope changed");
  assert.equal(proposal.stages.length, 10);
  const reviewBytes = readFileSync(resolve(packet, "FACTS-REVIEW.v2.md"));
  assert.equal(sha(reviewBytes), factsV2ReviewSha256, "Independent facts-v2 review changed");
  assert(reviewBytes.toString("utf8").includes(factsV2ProposalSha256), "Facts review lacks the frozen proposal pin");
  const themeBytes = readFileSync(resolve(packet, "THEME-PROPOSAL.json"));
  assert.equal(sha(themeBytes), themeV1ProposalSha256, "Preserved v1 proposal changed");
  assert.equal(sha(readFileSync(resolve(packet, "THEME-REVIEW.md"))), themeV1ReviewSha256, "Preserved theme review changed");
  const themes = JSON.parse(themeBytes.toString("utf8")) as {stages: Array<{figureKey: string; file: string; originalSha256: string; proposedSha256: string; changedFields: string[]}>};
  assert.equal(themes.stages.length, 10);
  const writingReceipt = JSON.parse(readFileSync(resolve(writing, "DATABASE-RECEIPT.json"), "utf8")) as {verifiedStoryCount: number;
    targets: Array<{figureKey: string; storySpecId: string; candidateSha256: string; stageSha256: string}>};
  assert.equal(writingReceipt.verifiedStoryCount, 10);
  same(readdirSync(resolve(packet, "facts-v2-stages")).filter(file => file.endsWith(".stage.json")).sort(), proposal.stages.map(pin => pin.file).sort(), "V2 stage-directory membership changed");
  const result = proposal.stages.map(pin => {
    assert(!pin.file.includes("/") && !pin.file.includes("\\") && pin.file.endsWith(".stage.json"), "Invalid approved stage filename");
    const originalBytes = readFileSync(resolve(inputs, pin.file));
    const v1Bytes = readFileSync(resolve(packet, "proposed-stages", pin.file));
    const proposedBytes = readFileSync(resolve(packet, "facts-v2-stages", pin.file));
    const stageSha256 = sha(originalBytes), v1Sha256 = sha(v1Bytes), productionStageSha256 = sha(proposedBytes);
    assert.equal(stageSha256, pin.originalWritingStageSha256);
    assert.equal(v1Sha256, pin.originalSha256); assert.equal(v1Sha256, pin.proposedV1StageSha256);
    assert.equal(productionStageSha256, pin.proposedSha256); assert.equal(productionStageSha256, pin.proposedV2StageSha256);
    const original = JSON.parse(originalBytes.toString("utf8")) as FigureStageRow;
    const v1 = JSON.parse(v1Bytes.toString("utf8")) as FigureStageRow;
    const proposed = JSON.parse(proposedBytes.toString("utf8")) as FigureStageRow;
    const theme = themes.stages.find(item => item.figureKey === pin.figureKey);
    assert(theme && theme.file === pin.file && theme.originalSha256 === stageSha256 && theme.proposedSha256 === v1Sha256, "V1 ancestry differs from its reviewed pins");
    const addition = themeAdditions[pin.figureKey as keyof typeof themeAdditions];
    same({...v1, themes: original.themes}, original, "V1 changed a field outside reviewed themes");
    same(v1.themes, addition ? [...original.themes, addition] : original.themes, "V1 theme additions changed");
    same(theme.changedFields, addition ? ["themes"] : [], "V1 changed-field ledger changed");
    if (!addition) assert.equal(stageSha256, v1Sha256, "An unapproved v1 stage changed bytes");
    same({...proposed, biographicalFacts: v1.biographicalFacts}, v1, "V2 changed a field outside biographicalFacts");
    same(pin.changedFields, ["biographicalFacts"], "V2 changed-field ledger changed");
    assert(proposed.biographicalFacts !== v1.biographicalFacts && typeof proposed.biographicalFacts === "string");
    const words = proposed.biographicalFacts.trim().split(/\s+/).length;
    assert(words >= 120 && words <= 180 && words === pin.proposedFactsWords && proposed.biographicalFacts.length === pin.proposedFactsCharacters, "Factual summary bounds changed");
    assert(new Set(proposed.themes).size === proposed.themes.length && proposed.themes.every(theme => THEME_VOCABULARY.includes(theme)), "Uncontrolled production themes");
    assert.equal(pin.unchangedCandidateFile, pin.file.replace(".stage.json", ".candidate.json"));
    const candidateBytes = readFileSync(resolve(inputs, pin.unchangedCandidateFile));
    const candidateSha256 = sha(candidateBytes);
    assert.equal(candidateSha256, pin.unchangedCandidateSha256);
    const draft = parseStorySpecDocument(JSON.parse(candidateBytes.toString("utf8")));
    assert(draft && draft.status === "draft"); same(draft.review, {}, "Frozen candidate review changed");
    const validation = validateStorySpec(draft, {forPublish: false}); assert(validation.valid && !validation.warnings.length, "Frozen candidate invalid");
    const written = writingReceipt.targets.find(item => item.figureKey === pin.figureKey);
    assert(written && written.storySpecId === draft.storySpecId && written.candidateSha256 === candidateSha256 && written.stageSha256 === stageSha256, "Writing receipt pins changed");
    same([proposed.figureKey, proposed.stageId, proposed.ageMin, proposed.ageMax], [draft.figureKey, draft.stageId, draft.episode.ageMin, draft.episode.ageMax], "Production identity or age changed");
    assert.equal(pin.figureKey, proposed.figureKey); assert.equal(pin.stageId, proposed.stageId);
    same(proposed.beats.map(beat => [beat.role, beat.text]), draft.arc.map(beat => [beat.role, beat.canonicalText]), "Canonical story prose changed");
    const factIds = new Set(draft.facts.map(fact => fact.factId));
    assert(pin.sentenceEvidence.length > 0 && pin.sentenceEvidence.every(sentence => sentence.candidateFactIds.length > 0 && sentence.candidateFactIds.every(id => factIds.has(id))), "V2 evidence ledger lacks mapped candidate facts");
    assert.equal(pin.sentenceEvidence.map(sentence => sentence.sentence).join(" "), proposed.biographicalFacts, "V2 evidence sentences do not cover exact summary");
    return {figureKey: pin.figureKey, storySpecId: draft.storySpecId, candidateSha256, stageSha256, productionStageSha256, original, proposed, draft};
  });
  assert.equal(new Set(result.map(input => input.figureKey)).size, 10); assert.equal(new Set(result.map(input => input.storySpecId)).size, 10);
  assert.equal(result.filter(input => input.original.biographicalFacts !== input.proposed.biographicalFacts).length, 10);
  return result;
}
